### ISSUE TITLE
Suggested Policy: Unused variable

### ISSUE THREAD

**Issue by neszt** [Perl-Critic/Perl-Critic#1015]
A new policy could detect unused variables. `$bar` is unused:

```perl
sub foo {
    my $bar;
}
```

**Comment by petdance** [comment]
There are already two.

https://metacpan.org/pod/Perl::Critic::Policy::Variables::ProhibitUnusedVariables is built in to Perl::Critic.

https://metacpan.org/pod/Perl::Critic::Policy::Variables::ProhibitUnusedVarsStricter is an add-on
