### ISSUE TITLE
Add Missing Dependencies to META.{json,yml} Files

### ISSUE THREAD

**Issue by chromatic** [Perl-Critic/Perl-Critic#1021]
Hi team!

I'm working on a work project that performs repeatable, isolated, hermetic builds of Perl distributions. Rather than using a CPAN client to install distributions, we evaluate a distribution's metadata statically, then build it in an isolated container with only its configuration or build dependencies present. Sometimes we find missing dependency information upstream. I think I've found some with the last couple of releases of `Perl-Critic`.

While these dependencies are enforced via `Build.PL`, they're not included in the configuration section of the `META.{json,yml}` files such that static analysis knows that these dependencies must be present to run the configuration/build step.

Would it be possible to update the bundling process to make these requirements clearer in the META files? I'd be happy to work on a pull request if it's desirable.

From my analysis so far, I think I'd expect to see something like this in the META files.

Configuration dependencies:

- `B::Keywords`
- `List::SomeUtils`
- `PPIx::QuoteLike`
- `Perl::Tidy`
- `Pod::Spell`
- `String::Format`

Runtime dependencies:

- `Fatal`
- `IO::String`
- `Pod::Parser`
- `Task::weaken`

Test dependencies:

- `Test::Deep`

**Comment by petdance** [comment]
Yes, PR, please. I don't know squat about Build.PL, but I'm glad to have the changes help you out.

Also note that we have dropped IO::String. (#997)

**Comment by petdance** [comment]
And List::SomeUtils is used everywhere, not just config.  But I guess the tool updates will take care of that.

**Comment by petdance** [comment]
Now I look back in the log and in 1.146 we dropped:

    Removed requirements and mentions of modules no longer used:
    * Fatal
    * IO::String
    * IPC::Open2
    * Pod::Parser
    * Task::Weaken

**Comment by petdance** [comment]
And Test::Deep got dropped as well.

**Comment by chromatic** [comment]
Thanks, let me see what I can do. Reproduction instructions look something like this:

 * install a fresh Perl with your favorite tool
 * download and unpack the latest `Perl-Critic` tarball
 * use your favorite CPAN tool to install the `configure` requirements listed in one of the `META` files
 * run `perl Build.PL` directly (without installing anything)
 * run `./Build` and capture any/all missing module failures
 * add those missing dependencies to the appropriate `configure` section and repeat
 
 I don't expect you to perform this work; I'm just documenting it here so it's visible what I'm doing and why.

**Comment by petdance** [comment]
Is this satisfied or is there more info I can help get you?

**Comment by chromatic** [comment]
I've just confirmed this is satisfied. Thanks for the quick response and merge!
