### ISSUE TITLE
Subroutines::ProhibitManyArgs counts signature argument names that contain underscores incorrectly

### ISSUE THREAD

**Issue by jgpuckering** [Perl-Critic/Perl-Critic#1027]
When signatures are used, this policy miscounts the number of arguments if the names of the arguments contain one or more underscores.

A signature such as ($a,$b) is seen as having two arguments, but one like ($a_x, $b) is seen as having three arguments.  It seems like variable names are being split on underscores and each part counted.

The following code will demonstrate this when run through `perlcritic -brutal` with the default policy of `max_arguments = 5`

```
use v5.32;
use warnings;

no warnings qw(experimental::signatures);
use feature qw(signatures);

sub foo ($a, $b, $c, $d_underscore, $e) {}
```

perlcritic will report "Too many arguments".  If $d_underscore is changed to $d, it doesn't report a warning.

**Comment by rbairwell** [comment]
Thanks for reporting this - I was confused as to why I was getting the error
`Too many arguments (Subroutines::ProhibitManyArgs, Severity 3) t/lib/Foobar.pm [Ln 215, Col 1]`
with:
`sub foo ( $self, $called_as, $expected_call_type ) {}`
using Perl Critic 1.150
