### ISSUE TITLE
Wrong error message if file called 0 does not exist

### ISSUE THREAD

**Issue by epa** [Perl-Critic/Perl-Critic#1040]
Normally perlcritic will report if a file specified does not exist.
```
% perlcritic xxx
No such file or directory: 'xxx'
```
But if the filename specified is 0 then the wrong error is reported.
```
% perlcritic 0
Problem while critiquing "0": Can't parse code: Did not pass a PPI::Tokenizer object to PPI::Lexer::lex_tokenizer
```

**Comment by petdance** [comment]
Did you run in to this in the wild, or discover it from inspecting the code?

**Comment by epa** [comment]
Hi, I believe I came across this while investigating another issue in perlcritic.  I was making a minimal test case and I used the filename 0 for my initial program, 1 for a shorter program that exhibits the same problem, 2 for still shorter and so on.

**Comment by petdance** [comment]
This doesn't happen on the current Perl::Critic 1.154.
