### ISSUE TITLE
NamingConventions::Capitalization - docs about package_exemptions not clear

### ISSUE THREAD

**Issue by Sadrak** [Perl-Critic/Perl-Critic#1043]
I wanted to allow some packages and had to look into the code why my `package_exemptions` is not working.

The naming is misleading, because not complete package-names are checked, only package-parts split on `::` are checked.

So my package `TLD::com::Baz` run 3 times again `package_exemptions`: `TLD`, `com` and `Baz`. So for my use case is is very hard to allow `TLD::[a-z]+::.+`, but at least the documentation should be clear about what is checked.

Please add a passage about packages are checked in parts (after a split) like this:

```
Please be aware, that C<package_exemptions> did not check complete package-names. For C<Foo::Bar::baz> is will check C<Foo>, C<Bar> and C<baz> sequentially.
```

**Comment by petdance** [comment]
Done. Thank you.   435846a3
