### ISSUE TITLE
Policy: Check for illegal illegal open source module licensing

### ISSUE THREAD

**Issue by thaljef** [Perl-Critic/Perl-Critic#117]
RT Ticket: http://rt.cpan.org/Ticket/Display.html?id=24887
Requested On: Mon Feb 12 01:53:33 2007
Requested By: adamk@cpan.org

---

A common pattern in CPAN modules is to have something like the following.

In fact, Perl::Critic does it itself!

---

=head1 COPYRIGHT

Copyright (c) 2005-2007 Jeffrey Ryan Thalhammer. All rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself. The full text of this license can
be found in the LICENSE file included with this module.

---

There's information, from the TPF lawyers via Allison I seem to recall
(although I could be wrong that it was from her) that this licensing
idiom is incorrect, and illegal.

Specifically, the "All rights reserved", since by making it free
software you are giving away certain specific rights.

The correct idiom for modules which have the "This program is free
software"... "the same terms as Perl itself" is to REMOVE the "All
rights reserved." and just have.

---

=head1 COPYRIGHT

Copyright (c) 2005-2007 Jeffrey Ryan Thalhammer.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself. The full text of this license can
be found in the LICENSE file included with this module.

---

For free software (which is the only subset of documents to which this
applies) I could classify this as a severity 1, as it can make the
software illegal to distribute.

**Comment by petdance** [comment]
I think that examining licenses is outside the scope of Perl::Critic.
