### ISSUE TITLE
Recognize 'Modern::Perl'

### ISSUE THREAD

**Issue by thaljef** [Perl-Critic/Perl-Critic#270]
RT Ticket: http://rt.cpan.org/Ticket/Display.html?id=43457
Requested On: Fri Feb 20 02:54:16 2009
Requested By: EDAVIS@cpan.org

---

The module Modern::Perl packages up several 'best practice' options into
one line.  You can just say

   use Modern::Perl;

and it turns on warnings, strict, 5.010, and C3 method resolution.

The policies RequireUseStrict and RequireUseWarnings should recognize
that Modern::Perl turns on these options.

**Comment by thaljef** [comment]
`Modern::Perl` and some other modules were added in 25c3929 and 2909d8a. I think I've covered the most common ones. But I'm not even going to attempt to cover all of them. Additional modules can be added via your `.perlcriticrc` configuration.

**Comment by epa** [comment]
Thanks for working on this.

**Comment by thaljef** [comment]
Shipped today as Perl-Critic-1.124.
