### ISSUE TITLE
Add MANIFEST to the repository

### ISSUE THREAD

**Issue by thaljef** [Perl-Critic/Perl-Critic#274]
RT Ticket: http://rt.cpan.org/Ticket/Display.html?id=43908
Requested On: Fri Mar 06 10:43:23 2009
Requested By: mschwern@cpan.org

---

I'm reopening this because I'm again working on Perl-Critic from the
repository and, once again, the tests are failing because of the missing
MANIFEST.  Once I generate the MANIFEST tests are still failing and I
can't tell if it's because the MANIFEST was generated incorrectly or if
something else is wrong.

> Also, if something is being regenerated, you shouldn't keep it around.

That's garbled version control dogma.  The actual rule is if something
is being generated **differently on different machines** you shouldn't
check it in.  For example MakeMaker's Makefile.

There's nothing wrong with checking in a generated file which is
supposed to be the same for everybody (ex. MANIFEST and META.*).  In
fact it's beneficial.
- Like any other file in the distribution, it is useful to track
  its contents at different points in the history for historical
  bug investigations.
- It avoids mistakes resulting from differing build environments.

Most importantly, it removes a barrier to new developers.  Ease of use
should trump version control dogma.  As much as possible, the code
should work straight out of the repository.

I would request somebody other than Elliot in the Perl::Critic project
respond please.  His selective single line responses are dismissive and
disrespectful.

**Comment by jonasbn** [comment]
The MANIFEST file is in the repository and have been for some time:

- https://github.com/Perl-Critic/Perl-Critic/commit/59b05e08846eb45f1426b9957da0cd092eb19ecc

I believe this issue can be closed
