### ISSUE TITLE
Add support for translated editions of PBP

### ISSUE THREAD

**Issue by thaljef** [Perl-Critic/Perl-Critic#280]
RT Ticket: http://rt.cpan.org/Ticket/Display.html?id=44618
Requested On: Fri Mar 27 02:52:44 2009
Requested By: dolmen@cpan.org

---

I have the french edition of PBP called "De l'art de programmer en Perl".

Perl::Critic tells me: "See page 184 of PBP". This is hard to track for
me as page numbers are different in my edition.

Adding support for other editions of PBP (translated messages,
translated page numbers) would fix this.

**Comment by petdance** [comment]
I can't imagine that we'll actually do this.
