### ISSUE TITLE
False positive for ValuesAndExpressions::ProhibitCommaSeparatedStatements

### ISSUE THREAD

**Issue by thaljef** [Perl-Critic/Perl-Critic#297]
RT Ticket: http://rt.cpan.org/Ticket/Display.html?id=48033
Requested On: Mon Jul 20 14:41:49 2009
Requested By: PackyAnderson@gmail.com

---

I've found another false positive:

package main;
use strict;
use warnings;
sub func {}
my %hash;
func( { %hash, bar => 2 } );
1;

Because the direct parent of the code containing the comma parses out
to be a PPI::Structure::Block, it's mistakenly flagging the hashref as
violating this policy.

I've actually worked up a patch that I think fixes this, but I wanted
to open a ticket for it first so I could reference it in my patch to
the ProhibitCommaSeparatedStatements.run file.

Thanks,
-packy
## 

Packy Anderson

Email:  PackyAnderson@gmail.com

**Comment by tomhukins** [comment]
I encountered this bug while using old versions of PPI and Perl::Critic.  However, with Perl::Critic version 1.130 and PPI 1.236 I no longer see this behaviour, so I suggest closing this bug report as fixed in the most recent versions.

**Comment by petdance** [comment]
Thanks, Tom.
