### ISSUE TITLE
Double-sigil dereference $% (possibly false positive)

### ISSUE THREAD

**Issue by thaljef** [Perl-Critic/Perl-Critic#339]
RT Ticket: http://rt.cpan.org/Ticket/Display.html?id=56624
Requested On: Thu Apr 15 03:47:42 2010
Requested By: JARIAALTO@cpan.org

---

Double-sigil dereference at line 7, column 7. See page 228 of PBP.

```
 1  #!/usr/bin/perl
 2  use strict;
 3  
 4  my %hash;
 5  my $ref = \%hash;
 6  
 7  print %$href;
```

The use of "%$" is quite common, likewise for the "@$ref"

**Comment by petdance** [comment]
> print %$href;

That's exactly what this policy was intended to detect.
