### ISSUE TITLE
Quotes used with an empty string (false positive)

### ISSUE THREAD

**Issue by thaljef** [Perl-Critic/Perl-Critic#344]
RT Ticket: http://rt.cpan.org/Ticket/Display.html?id=56629
Requested On: Thu Apr 15 04:33:29 2010
Requested By: JARIAALTO@cpan.org

---

Quotes used with an empty string at line 4, column 31. See page 53 of 
PBP.

```
 1  #!/usr/bin/perl
 2  use strict;
 3  
 4  my $var = $debug ? "DEBUG:" : "";
```

This is a proper initialization.

**Comment by petdance** [comment]
Works as intended.
