### ISSUE TITLE
[PATCH] "use base 'Exporter'" => "use Exporter 'import'"

### ISSUE THREAD

**Issue by thaljef** [Perl-Critic/Perl-Critic#460]
RT Ticket: http://rt.cpan.org/Ticket/Display.html?id=75300
Requested On: Sat Feb 25 03:42:14 2012
Requested By: dolmen@cpan.org

---

"base.pm" is an old module that is preserved for compatibility, but that
is nowadays replaced by 'parent.pm' for the only common use case.
The "use base 'Exporter'" is a special case that has a more efficient
and completely documented way of avoiding 'base.pm':
   use Exporter 'import';

Here is a patch that basically does this:
- use base 'Exporter';
- use Exporter 'import'; 

Making a Critic policy of this is left as an exercice to the reader.
## 

Olivier Mengu? - http://perlresume.org/DOLMEN

**Comment by petdance** [comment]
Closed since it was applied.
