### ISSUE TITLE
Perl::Critic::Policy::Subroutines::ProhibitReturnSort  documentation question

### ISSUE THREAD

**Issue by thaljef** [Perl-Critic/Perl-Critic#537]
RT Ticket: http://rt.cpan.org/Ticket/Display.html?id=89904
Requested On: Wed Oct 30 11:14:05 2013
Requested By: NHORNE@cpan.org

---

Should:

```
@sorted_list = sort @list;
   return @sort        # ok
```

Be:

```
@sorted_list = sort @list;
   return @sorted_list        # ok
```

**Comment by petdance** [comment]
This has been fixed.  c0d57d260be0bafe7df8ce449274e4ccf5689338
