### ISSUE TITLE
Incorrect docs: “If a regexp match fails, then any capture variables ($1, $2, ...) will be undefined.”

### ISSUE THREAD

**Issue by FGasper** [Perl-Critic/Perl-Critic#566]
The statement:

If a regexp match fails, then any capture variables ($1, $2, ...) will be undefined.

… is untrue.

What is true is that $1, $2, etc. are UNAFFECTED by failed regexp matches.

This is an important distinction since these are globals.

**Comment by petdance** [comment]
Fixed in 92ed2a0.  Thanks.
