### ISSUE TITLE
RequireFilenameMatchesPackage gives false positives when testing temp copy of module

### ISSUE THREAD

**Issue by genehack** [Perl-Critic/Perl-Critic#568]
I use flycheck's perl-perlcritic checker. Flycheck works by making a temporary copy of a file (at a location under $TMPDIR). This copy has the same basename as the original file, but the directory hierarchy under `lib` is _not_ reproduced. So, for example when checking a file from `lib/Foo/Bar.pm`, the actual checked file will be at `/tmp/30940439/Bar.pm`.

This makes RequireFilenameMatchesPackage fail, even though the basename of the file and the terminal element of the package declaration match. This contradicts the documentation of the policy:

```
Therefore, this Policy requires the last component of the first package name
declared in the file to match the physical filename
```

**Comment by petdance** [comment]
@genehack submitted a PR which has since been deleted.  The change was roughly this:

```
          # Mismatched name
-         return $self->violation( $DESC, $EXPL, $pkg_node );	
+         return $self->violation( $DESC, $EXPL, $pkg_node )
+             unless $matched_any;
```
