### ISSUE TITLE
Perl::Critic::Policy::References::ProhibitDoubleSigils and postfix deref

### ISSUE THREAD

**Issue by zdm** [Perl-Critic/Perl-Critic#578]
Perl::Critic::Policy::References::ProhibitDoubleSigils policy recognize hash postfix dereference ->%\* as double sigil and throw error.

**Comment by elcamlost** [comment]
PPI now supports postfix dereferencing. Maybe there is a way to support them as critic policy too?

**Comment by zdm** [comment]
PPI already supported required functionality.
https://github.com/adamkennedy/PPI/issues/88

**Comment by petdance** [comment]
What do we need to do to get this checking worked into Perl::Critic?  Do you have a case of some code that fails that we can put into a test case?

**Comment by zdm** [comment]
yes, please, use this sample
```
$sref->$*;
$aref->@*;
$aref->$#*;
$href->%*;
$cref->&*;
$gref->**;
```

Currently this policy produces error
```
References::ProhibitDoubleSigils - Double-sigil dereference
```

**Comment by petdance** [comment]
Thanks for that.  Someone that's not me will be able to pick that up and run with it, I hope.

**Comment by zdm** [comment]
Here is the comment from @wchristian 
```
That's not a bug in PPI, that's a bug in that policy which wasn't updated to take into account that Token::Cast can now NOT have a block after it, if it is preceeded by a dereference operator.
```

**Comment by petdance** [comment]
This will go out in whatever the next release after 1.140 is.
