### ISSUE TITLE
Tweak POD for use with Dist::Zilla

### ISSUE THREAD

**Issue by thaljef** [Perl-Critic/Perl-Critic#6]
I think this just means that we take all the NAME sections and turn them into `#ABSTRACT` comments.  But it may not be necessary.

**Comment by petdance** [comment]
I don't think we're going to switch off of Module::Build any time soon.

**Comment by xsawyerx** [comment]
Is there a particular value in staying with `Module::Build`, other than "We don't have time right now to move"? (That's an absolutely fine reason.)

**Comment by petdance** [comment]
That's about it.  I was looking through the tickets to see if there was anything that we could definitely close, and this seemed like one of them.
