### ISSUE TITLE
References::ProhibitDoubleSigils takes issue with multiplication

### ISSUE THREAD

**Issue by Amorymeltzer** [Perl-Critic/Perl-Critic#604]
I get a ProhibitDoubleSigils error with this type of code: `my $v = $opts{r}*$g;`
No error is thrown for: `my $v = $opts{r}* $g;` or `my $v = $g*$g;`, but one DOES appear with `my $v = $opts{r} *$g;`
It looks like as long as the last non-whitespace character is a `}`, a `*` touching `$` will trigger the warning.  Doesn't happen with `@` or `%`.

perlcritic 1.122, perl 5.20.0

**Comment by Amorymeltzer** [comment]
Fixed upstream

**Comment by petdance** [comment]
Is there a test we can add to Perl::Critic to verify it's been fixed in PPI?  It would be good if we could announce it as a fix in Perl::Critic, even though the fix is in PPI.

**Comment by Amorymeltzer** [comment]
Tests added in #969
