### ISSUE TITLE
Policy proposal: ProhibitYaddaOperator

### ISSUE THREAD

**Issue by thaljef** [Perl-Critic/Perl-Critic#609]
The yadda `…` operator is not something you'd want in production code. But it is perfectly useful in less critical environments. So this wouldn't be a policy that you use _all_ the time. Perhaps then it would make sense to have this at severity 4 or 3.

**Comment by bentglasstube** [comment]
I thought GitHub would automatically find it, but there is a PR for this at #617

**Comment by glauschwuffel** [comment]
I think this can be closed since it's implemented and released: https://metacpan.org/pod/Perl::Critic::Policy::ControlStructures::ProhibitYadaOperator
