### ISSUE TITLE
TestingAndDebugging::RequireUseStrict false positive with MooseX::Singleton

### ISSUE THREAD

**Issue by jpepersack** [Perl-Critic/Perl-Critic#616]
This test correctly passes a vanilla Moose class, but when converted to a MooseX::Singleton it fails.   There's another open related issue for the same thing with Moo.    

I would suspect that anything in the Moo* hierarchy that is a replacement for 'use Moose' is going to have the same issue.

**Comment by thaljef** [comment]
`MooseX::Singleton` and some other modules were added in 25c3929 and 2909d8a. I think I've covered the most common ones. But I'm not even going to attempt to cover all of them. Additional modules can be added via your `.perlcriticrc` configuration.

**Comment by thaljef** [comment]
Shipped today as Perl-Critic-1.124.
