### ISSUE TITLE
Use of uninitialized value in string eq at /usr/share/perl5/Perl/Critic/Policy/ValuesAndExpressions/ConstantBeforeLt.pm line 114.

### ISSUE THREAD

**Issue by epa** [Perl-Critic/Perl-Critic#620]
I get a warning 

Use of uninitialized value in string eq at /usr/share/perl5/Perl/Critic/Policy/ValuesAndExpressions/ConstantBeforeLt.pm line 114.

I have found a minimal test case for this.  The minimal input file is not valid Perl code; however, I did see the warning also on input files which were valid Perl.  I suggest that perlcritic should not produce the warning even on syntactically badly-formed input.

Here's the minimal test case:

````
sub y {
````

Running this through perlcritic --brutal gives the above warning, among other messages.

**Comment by thaljef** [comment]
`ValuesAndExpressions::ConstantBeforeLt' is not a core module. It comes from [Perl-Critic-Pulp](https://metacpan.org/release/Perl-Critic-Pulp)

I have re-submitted this bug [here](https://rt.cpan.org/Ticket/Display.html?id=102408)

**Comment by epa** [comment]
Thanks
