### ISSUE TITLE
Scalar::List::Utils 1.35 needed

### ISSUE THREAD

**Issue by epa** [Perl-Critic/Perl-Critic#626]
The latest Perl::Critic has code in ProhibitUnusedPrivateSubroutines.pm:

```
use List::Util qw(any);
```

But `any` was only recently added to that module.  Older versions of List::Util don't provide it.  You need a dependency on Scalar::List::Utils 1.35 or greater.

See http://cpansearch.perl.org/src/PEVANS/Scalar-List-Utils-1.41/Changes

**Comment by pghmcfc** [comment]
Or you could just use List::MoreUtils qw(any) like everywhere else in the code...

**Comment by oalders** [comment]
This issue should have been closed by the referenced commit.
