### ISSUE TITLE
Add Test::Most to equivalent strict modules in TestingAndDebugging::RequireUseStrict

### ISSUE THREAD

**Issue by harleypig** [Perl-Critic/Perl-Critic#647]
https://metacpan.org/requires/distribution/Test-Most?sort=[[2,1]] shows there are 469 modules that depend on Test::Most, the first 150 of which were last updated this year. I don't know if those are high enough numbers, but I'm including them just in case. :]

**Comment by petdance** [comment]
See also #740

**Comment by petdance** [comment]
I've opened #796 as an alternative to continuing to maintain the list of equivalency modules.
