### ISSUE TITLE
incorrect error message

### ISSUE THREAD

**Issue by johndeighan** [Perl-Critic/Perl-Critic#680]
The following code, when run through Perl::Critic gives me the error: "$val1" is declared but not used.
It should not:

use strict;
use warnings;

test();

# -----------------------------------------------------

sub test {

my $val2;

(my $val1, $val2) = func();
print("val1 = $val1\n");
print("val2 = $val2\n");
return;
} # test()

# -----------------------------------------------------

sub func {

return ( 'abc', 'xyz' );
} # func()

**Comment by mcreenan** [comment]
Can you post your perlcriticrc and invocation?  I am unable to reproduce that error for this source code.

**Comment by rdsteiner** [comment]
Also unable to reproduce.

**Comment by johndeighan** [comment]
This is an old post - from January. At that time I was using Perl::Critic 1.121. When I upgraded to Perl::Critic 1.126, the problem went away, so I'm closing this issue. Thanks for looking at this.
