### ISSUE TITLE
Komodo integration link dead, here is corrected link

### ISSUE THREAD

**Issue by code-read** [Perl-Critic/Perl-Critic#685]
Page http://search.cpan.org/~elliotjs/Perl-Critic-1.106/extras/KomodoIntegration.pod shows the following link for information on Komodo integration:

For more information, have a look at http://trentm.com/blog/archives/2009/04/02/komodo511/

The above is a dead link; the following is where the information was apparently moved to:

http://trentm.com/2009/04/komodo-511-fixes-path-mode-in-fast-open-dialog-perlcritic-integration.html

**Comment by petdance** [comment]
This file is no longer part of the Perl::Critic distribution.
