### ISSUE TITLE
Bad internal links for RequireBlockMap & RequireBlockGrep

### ISSUE THREAD

**Issue by cebjyre** [Perl-Critic/Perl-Critic#694]
The ProhibitStringyEval and ProhibitStringySplit docs have "SEE ALSO" sections that link to Perl::Critic::Policy::ControlStrucutres::RequireBlock... rather than the correct Perl::Critic::Policy:: BuiltinFunctions::RequireBlock... version

**Comment by cebjyre** [comment]
I've just created pull request #695 which fixes this

**Comment by petdance** [comment]
I've manually made these changes at 0e09ec3.  Thanks!
