### ISSUE TITLE
theme --core Does Not Properly Disable RequirePod

### ISSUE THREAD

**Issue by wbraswell** [Perl-Critic/Perl-Critic#712]
When this is installed:
https://metacpan.org/pod/Perl::Critic::Policy::Documentation::RequirePod

Then apparently, in some cases it will not be disabled by `--theme core`.

See here for more info:
https://github.com/wbraswell/rperl/issues/28

**Comment by wbraswell** [comment]
@thaljef 
As soon as you use GitHub to set me as an "owner" of the Perl-Critic organization, then I will be able to assign this issue (and others) to myself and try to start fixing bugs, etc.
https://github.com/orgs/Perl-Critic/people

**Comment by thaljef** [comment]
That's a problem with the policy module, not Perl::Critic itself. The author has mistakenly declared that it is a "core" module. See here:

https://metacpan.org/source/AUTINITY/Perl-Critic-Policy-Documentation-RequirePod-0.005/lib/Perl/Critic/Policy/Documentation/RequirePod.pm#L21

**Comment by wbraswell** [comment]
@thaljef 
Thanks for the info!  I have filed a new bug:
https://github.com/autinitysystems/Perl-Critic-Policy-Documentation-RequirePod/issues/1
