### ISSUE TITLE
Tweak perlcriticrc for Sonar

### ISSUE THREAD

**Issue by petdance** [Perl-Critic/Perl-Critic#721]
@otrosien has set up Sonar at http://sonarqube.racodond.com/component_issues?id=Perl-Critic

We are getting false positives, and so need to be adjusted somehow in the config.

For example, t/06_violation.d/source/Line.pm is flagged for an expression `eval`, but that's OK because all the files in that directory are meant to trigger warnings, because they're part of the test suite.

**Comment by otrosien** [comment]
In this case we can flag the false positive inside Sonar as well, might be easier.

**Comment by otrosien** [comment]
What about the other ones?

**Comment by petdance** [comment]
I would think we'd want to tell Sonar to ignore all of t/06_violation.d/source/ since everything in there will have some kind of violation.

> What about the other ones?

If you're referring to the other eval failures, that's a separate issue.  This issue is just about getting Sonar to not give false positives on directories that it should not be checking.

**Comment by otrosien** [comment]
simplistic approach: `grep -v t/06_violation.d/ perlcritic_report.txt`

**Comment by otrosien** [comment]
I don't even know if perlcritic command-line args or rc-file would allow you to exclude certain directorie, so I'll just go ahead and add a "grep -v" to the sonar-report script if you don't mind.

**Comment by otrosien** [comment]
FYI: Unfortunately the free service by David Racodon has been shut down. I will try to get the data from a backup and find a new place to host this.

**Comment by petdance** [comment]
When you find it, please open a new ticket.  Thanks for keeping an eye open.

**Comment by petdance** [comment]
@otrosien Is Sonar gone entirely?  Should we get rid of the sonar configurations in the Perl::Critic codebase?

**Comment by otrosien** [comment]
I wrote to the admin, he doesn't have backups. So, if we want to re-enable sonarqube, we need to find a new hosting location, and start from scratch. I'm really sorry for that...

**Comment by petdance** [comment]
So can I toss the all the Sonar configurations?

**Comment by otrosien** [comment]
Sure you can, yes. We can always re-introduce them when we find a new home for it. You can also create a ticket as a reminder to fix it. The configs don't hurt right now, do they?

**Comment by petdance** [comment]
The configs hurt only as much as any other unused code/configs/etc, which is to say that they're just noise.

I've deleted them in this commit: c92d5468a20785d8f51df21bbbcb7d2ed4ff0447.  I'm linking it here so that we have an easy way to find them again.

**Comment by petdance** [comment]
Thanks for your work on this.  I'd love to have it back up and running.
