### ISSUE TITLE
Add a format string for the offending line

### ISSUE THREAD

**Issue by petdance** [Perl-Critic/Perl-Critic#731]
I'd like a `%L` that shows the full line of code that caused the error, so instead of

    Dev/facet-stats: Private subroutine/method used at line 31, column 46.  Use published APIs.

I could set up my format string to show:

    Dev/facet-stats: Private subroutine/method used at line 31, column 46.  Use published APIs.
        my $class = FacetController->_facet_class( $id );

**Comment by thaljef** [comment]
%r should do something like that.

**Comment by petdance** [comment]
Grraaaarrrrrr!  I read the list in `man perlcritic` a zillion times and missed it.  Thanks.

**Comment by petdance** [comment]
`%r` shows the statement that caused the problem, but it doesn't show the line of code itself.  Specifically, I'm interested in any comments that might appear on that line of code.

I've got code where `%r` shows

    my $quoteids = @_;

when I want it to show:

    my $quoteids = @_; # XXX Nothing in here looks at the quoteids.  See RT 4023 for details.

**Comment by petdance** [comment]
My mistake.  It DOES show the full line.

**Comment by petdance** [comment]
It seems that %r only shows the offending statement, not the line of code.  For example, I have things like this:

    my $is_proxy = shift; # XXX This variable is unused.  What behavior should it be checking that it isn't?  See RT 4320 for details.

but it only shows in my error listings as

    my $is_proxy = shift; # XXX This variable is unused.  What behavior should it be checking that it isn't?

Worse, I've got a statement line this:

    my ($url, $page_title) = $source =~ /^(.*?)\s\((.*?)\)\s*$/;

That %r shows as:

    $url, $page_title

**Comment by petdance** [comment]
This is a bug that's been fixed elsewhere.
