### ISSUE TITLE
violation source line %r display when blank lines in element

### ISSUE THREAD

**Issue by kryde** [Perl-Critic/Perl-Critic#734]
In debian packaged perlcritic 1.126, if an element contains blank lines then the source %r displayed for a violation is wrong.  For example perlcritic --severity 1 --verbose=9 foo.pl attached shows

[ValuesAndExpressions::RequireInterpolationOfMetachars] String *may* require interpolation at line 3, near ''.  (Severity: 1)

whereas I hoped it would be "near '@bar'".

Some inputs provoke an unitialized value warning too, for example bar.pl attached run similarly.

In Perl::Critic::Violation I think the split in _line_containing_violation() collapses blank lines since \s* matches newlines.  Some of the flags are trying to affect that are they?  For the uninitialized I think $inx would be compared to $#lines not @lines.  I get some joy from splitting on newline and trimming leading whitespace later like diff below.

[foo.pl.txt](https://github.com/Perl-Critic/Perl-Critic/files/746470/foo.pl.txt)
[bar.pl.txt](https://github.com/Perl-Critic/Perl-Critic/files/746475/bar.pl.txt)
[Violation.pm.diff.txt](https://github.com/Perl-Critic/Perl-Critic/files/746484/Violation.pm.diff.txt)

**Comment by xsawyerx** [comment]
I believe it's the same bug #702 fixes.

**Comment by bar** [comment]
@kryde mhhh? I don't think you wanted to at handle me...

**Comment by petdance** [comment]
Sorry about that.  It's an artifact of referring to the Perl variable `@bar`.

**Comment by petdance** [comment]
@xsawyerx Is this fixed? Is there a test for it?

**Comment by xsawyerx** [comment]
@petdance On it. Expect one this evening.

**Comment by xsawyerx** [comment]
Done: #758.
