### ISSUE TITLE
Mailing List Spam

### ISSUE THREAD

**Issue by wbraswell** [Perl-Critic/Perl-Critic#736]
We are receiving spam via the mailing list.

@thaljef  Can you please transfer mailing list admin ownership to myself and @petdance ?

Thanks!

```
Return-Path: dev-return-3210253+william.braswell=FOO.com@perlcritic.tigris.org
Received: from FOO by
 server with LMTP; Fri, 17 Feb 2017 01:58:13 +0000 (UTC)
Received: from FOO
	for <william.braswell@FOO.com>; Fri, 17 Feb 2017 01:58:13 +0000 (UTC)
X-Real-Recipient: william.braswell@FOO.com
Received: from sc157-tigr.sjc.collab.net (unknown [204.16.104.226])
	by FOO with ESMTP
	for <william.braswell@FOO.com>; Fri, 17 Feb 2017 01:58:12 +0000 (UTC)
Received: from sc157-tigr.sjc.collab.net (localhost [127.0.0.1])
	by sc157-tigr.sjc.collab.net (Postfix) with ESMTP id 60DF154057A;
	Thu, 16 Feb 2017 17:58:16 -0800 (PST)
Date: Thu, 16 Feb 2017 17:58:15 -0800 (PST)
From: webpost@tigris.org
Reply-To: dev <dev@perlcritic.tigris.org>
To: dev@perlcritic.tigris.org
Message-ID: <1786982045.27252.1487296695260.JavaMail.httpd@localhost>
Subject: [Perl-Critic] Nauczyciela. pryskac Przestancie.
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
List-Unsubscribe: <dev-unsubscribe@perlcritic.tigris.org>
List-Id: <dev.perlcritic.tigris.org>
Precedence: bulk
List-Subscribe: <dev-subscribe@perlcritic.tigris.org>

Acai Berry - How Come Acai Berry Supplement Ideal For You? 
...

------------------------------------------------------
http://perlcritic.tigris.org/ds/viewMessage.do?dsForumId=4230&dsMessageId=3210253

To unsubscribe from this discussion, e-mail: [dev-unsubscribe@perlcritic.tigris.org].
```

**Comment by thaljef** [comment]
I have restricted web posting to the mailing list. This should prevent further spam.

I would advise you to create a new mailing list somewhere else. The current list is run by tigris.org which also used to host the source code, before we moved to github. It has always been problematic because the only way to prevent spam is to restrict access to registered users. IMHO, that just barriers to discussion. Better to choose a mail system that is open to all but has decent spam filtering.

**Comment by petdance** [comment]
I've created a new mailing list over at Google Groups.

https://groups.google.com/d/forum/perl-critic

**Comment by wbraswell** [comment]
@petdance 
I have applied for membership in the Google group, please set me as an admin/owner, thanks!

@thaljef 
How can we migrate everyone from the old Tigris list to the new Google list?

**Comment by petdance** [comment]
I don't think we should migrate people.  If they want to move, they can.  Who knows how many people are on the list that really don't care any more?

**Comment by wbraswell** [comment]
@petdance 
1.  Thank you for adding me to the new Google group, can you please set me as a group admin?
2.  If we're not going to migrate anyone off the old group, are we at least going to make an announcement on the old group with a link to the new group?

**Comment by petdance** [comment]
1) Done.

2) I did post to the old group.  Probably we should post a reminder to it every week for a month and then shut the thing down.
