### ISSUE TITLE
-single-policy is not enough to ignore bogus policies

### ISSUE THREAD

**Issue by guest20** [Perl-Critic/Perl-Critic#739]
If I have some critic rules that only work in some places (like, say, on a CI machine), something like
`lib/Perl/Critic/Policy/Bogus.pm`:
```
package Perl::Critic::Policy::Bogus;
use Something::Not::Installed::On::My::Laptop;
...
1
```
I won't ever be able to create a critic object with that thing in `@INC`, even if I explicitly request that policy not be loaded:
```
  $critic = Perl::Critic->new( '-severity'=> 1,
            '-single-policy' => 'ValuesAndExpressions::PreventSQLInjection',)
```

Here the `Module::Pluggable` usage in `Perl::Critic::PolicyFactory` passes `require =>1`, and then filters out those policies that don't match `-single-policy`, meaning that `::Policy::Bogus` is loaded even when I ask for that to not happen. 

It seems like this is exactly the use-case intended for [Module::Pluggable's only](https://metacpan.org/pod/Module::Pluggable#only), but perhaps simply not passing `require =>1` then filtering the list and doing the require separately would be enough?

**Comment by thaljef** [comment]
Are these rules that you wrote yourself or something you pulled off of CPAN?

**Comment by guest20** [comment]
They are rules we wrote ourselves, but I can't imagine that making a difference.

If I have all my critic rules in one repo, I can't run any of them unless all their depends are satisfied.

**Comment by thaljef** [comment]
It's your rule, so it's up to you to decide what should happen if the dependencies aren't there. So you might use a construct like `$has_dependency = eval { require Some::Dependency}` or [Class::Load](https://metacpan.org/pod/Class::Load) to load modules.

After construction, `initialize_if_enabled($config)` is called on each Policy object, which gives you a chance to indicate that the Policy should not be invoked by returning false. See [POD](https://metacpan.org/pod/Perl::Critic::Policy#METHODS) for details.

I can understand your perspective on the `--single-policy` option. But that issue goes away if the Policy module is well-behaved. Perl::Critic can't know which modules should or should not work in any particular environment. Does that makes sense.

**Comment by guest20** [comment]
I don't really want to agree with you because it means I have to go and mess with those other policies, but I think you're right, it doesn't make sense with the way the "normal" use cases go.

Thanks for your time.

(I ended up sticking a copy of `Perl::Critic::PolicyFactory` earlier in `@INC` to adjust its opinion manually, but that won't end up in production, hopefully).
