### ISSUE TITLE
Perl::Critic::Policy::TestingAndDebugging::RequireUseStrict should know about Test::Class::Moose

### ISSUE THREAD

**Issue by skington** [Perl-Critic/Perl-Critic#746]
The following code generates a failure under the standard policy:

> package Test::Whatever;
> 
> use Test::Class::Moose;
> with 'Role::Test';
> with 'Role::Test::Mocking';
> with 'Role::Test::WipeDatabase';

Specifically:

> Perl::Critic::Policy::TestingAndDebugging::RequireUseStrict: Code before strictures are enabled at .../Test/Whatever line 4, near with 'Role::Test';

Test::Class::Moose, like Moose, Moo and others, enables strictures in your package.

**Comment by petdance** [comment]
See also #740

**Comment by petdance** [comment]
Rather than maintaining a list of equivalent modules, we're going to add functionality to let people add their own via configuration.  See #796.
