### ISSUE TITLE
Upgrade to PPI 1.224

### ISSUE THREAD

**Issue by petdance** [Perl-Critic/Perl-Critic#754]
https://metacpan.org/release/PPI

**Comment by petdance** [comment]
I'm trying to find where PPI version is specified and I'm not seeing it.   I see nothing in Build.PL.

**Comment by thaljef** [comment]
Here: https://github.com/Perl-Critic/Perl-Critic/blob/dev/inc/Perl/Critic/BuildUtilities.pm#L47

**Comment by petdance** [comment]
Done. f087e0e
