### ISSUE TITLE
Make all the tests check version of P::C they are running against

### ISSUE THREAD

**Issue by petdance** [Perl-Critic/Perl-Critic#755]
In most of the .t files, there's an `our $VERSION = 1.126;`.  Is there any value to this?  If not, let's get rid of them.

**Comment by thaljef** [comment]
As I recall, @clonezone  and I took a hard line stance on this. Declaring a `$VERSION` in every file gives the consumer an assurance that every source file in the distro actually belongs together. I typically used something like [perl-reversion](https://metacpan.org/source/BDFOY/Perl-Version-1.013/examples/perl-reversion) to make it painless.

**Comment by petdance** [comment]
@clonezone Is this still relevant?

Looks like there are a few that have been missed:
```
$ ack "VERSION\s*=.*?'(1\.\d{3})'" --output='$1' -h --perl  | sort | uniq -c
      2 1.116
      2 1.121
      1 1.123
    249 1.126
```

**Comment by thaljef** [comment]
> Looks like there are a few that have been missed:

There might be a couple genuine outliers, but most of those are probably in POD or tests or some other context that warrants a different value for VERSION.

**Comment by petdance** [comment]
At least one of 'em is in `tools/ppidump`.  I haven't dug through the rest.

**Comment by thaljef** [comment]
I stand corrected; those are all genuinely wrong. They should all have matching $VERSION (if you choose to continue that policy).

**Comment by petdance** [comment]
@clonezone Do you have any thoughts on this?  If not, I'm going to remove the `$VERSION`s from all the tests.

**Comment by clonezone** [comment]
I prefer versions in everything.

**Comment by petdance** [comment]
Update all the .t files to verify the version of P::C that they are running against.  As it stands now, the `$VERSION` declarations in the .t files are potentially inaccurate unless they are tested.

**Comment by xsawyerx** [comment]
Something is odd here:

    Declaring a $VERSION in every file gives the consumer an assurance that every source file in the distro actually belongs together.

Firstly, was this ever disputed? Secondly, if it's all incremented automatically anyway, one can argue it's just as unintended as if they weren't versioned.

**Comment by petdance** [comment]
I think it makes sense to have all *.pm versioned, and there's a test to check the versioning, `t/00_versions.t`, that used to be in the `xt/` directory.

The versioning of *.t files as it stands right now doesn't do anything because they're just there.  What I imagine is replacing every `$VERSION = 1.126` with `assert_version( 1.126 )` so that we know all the tests are in sync with the libraries.

**Comment by petdance** [comment]
All tests now call `assert_version( $VERSION )` to make sure they sync up.  

ebf0640
