### ISSUE TITLE
Fix missing files warning from Build.PL

### ISSUE THREAD

**Issue by petdance** [Perl-Critic/Perl-Critic#756]
perl Build.PL gives

```
WARNING: the following files are missing in your kit:
        lib/Perl/Critic/PolicySummary.pod
        META.json
        META.yml
        README
```

What in the build process needs to get updated?

**Comment by clonezone** [comment]
Nothing.  They'll be generated.

**Comment by petdance** [comment]
Is there a way we can tell Build.PL not to worry about them?

**Comment by clonezone** [comment]
I don't think so without the warning being disabled when you really need it.

**Comment by petdance** [comment]
We can't tell it "Ignore these four files"?

I don't like having to Just Know that those are the four files it's OK to ignore.

**Comment by clonezone** [comment]
It is not OK to ignore them in general.

It is OK to ignore them if you are running Build.PL for the first time on a fresh checkout of the repository.
