### ISSUE TITLE
Remove all mentions of old tigris.org mailing list

### ISSUE THREAD

**Issue by petdance** [Perl-Critic/Perl-Critic#757]
There seems to be a lot of overlap between README.md and bin/perlcritic.  Is one generated from the other?

**Comment by clonezone** [comment]
There was no `README.md` in the old repository. It got added after the move: https://github.com/Perl-Critic/Perl-Critic/commits/dev/README.md

`README` gets generated as part of the build.

**Comment by petdance** [comment]
@thaljef Did you make something that replicates `bin/perlcritic` to/from `README.md`?  Or is the `README.md` a manual conversion of it?

**Comment by thaljef** [comment]
Pretty sure I used [pod2markdown](https://metacpan.org/pod/distribution/Pod-Markdown/bin/pod2markdown) or something similar.

**Comment by petdance** [comment]
See #760

**Comment by petdance** [comment]
Link to 
https://groups.google.com/d/forum/perl-critic

**Comment by petdance** [comment]
Done. 411d6a4
