### ISSUE TITLE
Uninitialized warnings when testing against PPI 1.224

### ISSUE THREAD

**Issue by xsawyerx** [Perl-Critic/Perl-Critic#759]
Testing dev (as of opening this ticket) against the latest PPI (1.224).

Not sure which milestone or label to use.

```
t/20_policies.t ............................... 1640/2706 Use of uninitialized value $word in pattern match (m//) at /home/sawyer/perl5/lib/perl5/PPI/Tokenizer.pm line 836.
Use of uninitialized value $word in pattern match (m//) at /home/sawyer/perl5/lib/perl5/PPI/Tokenizer.pm line 836.
```

**Comment by petdance** [comment]
Does this still give you a warning?  I don't get a warning on dev now, and I went back to a May 18 commit and didn't get a warning then, either.

I'm willing to say "OK, it's fixed" if you're not getting the warning now.

**Comment by xsawyerx** [comment]
I'll test it out today and let you know.

**Comment by xsawyerx** [comment]
Works on latest dev and PPI 1.236!
