### ISSUE TITLE
Remove the _without_optional_dependencies.t boilerplate

### ISSUE THREAD

**Issue by petdance** [Perl-Critic/Perl-Critic#762]
Apparently at one point there was some mechanism to build _without_optional_dependencies.t files.  Is this still relevant?  If not, get rid of the boilerplate.

**Comment by petdance** [comment]
Done 977dd33

**Comment by clonezone** [comment]
Undo this.

This is mandatory.

These tests are there to ensure that things work when optional modules are not installed.

**Comment by petdance** [comment]
Say more, please.  I could find no way to get these to fail without them.

**Comment by clonezone** [comment]
Tests that you don't run can't fail.

You need to run most tests twice: once with the optional modules available and once without.

Use Module::Build. Do **not** use EU::MakeMaker. If you run `./Build dist`, the templates to run without the optional modules available will be generated.

**Comment by clonezone** [comment]
All the development functionality is built using Module::Build. EU::MakeMaker is only supported for installation.

**Comment by petdance** [comment]
> Tests that you don't run can't fail.

That's why I said "I could find no way to get these to fail".

> You need to run most tests twice: once with the optional modules available and once without.

So how do you do that?

> Use Module::Build. Do not use EU::MakeMaker. If you run ./Build dist, the templates to run without the optional modules available will be generated.

I'm not using EU::MakeMaker.  I ran `./Build dist` just now and everything ran without error.  I then unzipped the tarball into a temp directory and did the same thing with that, and had no problem.  And that unzipped tarball doesn't match any _without_optional_depencies.t files.

How can I get this to fail?

**Comment by clonezone** [comment]
Modify a Policy to fail if one of the optional modules is not available.

**Comment by clonezone** [comment]
And the `_without_optional_depencies.t` don't end up in the tarball because they're author-only tests.

**Comment by clonezone** [comment]
\*sigh\*

Someone removed `xt/82_optional_modules.t`. This test needs to be restored.

**Comment by petdance** [comment]
Looks like @thaljef removed the optional modules system.  This happened somewhere between 1.121 and 1.126.

a3106c92b98fa7aaacab444f9724882d808a2cd4

    All recommended/optional dependencies are now required.
    
    This ensures a consistent & optimal experience for all users.
    Also, it makes our code a lot simpler since we don't have to
    generate wrappers that run all the tests without the optional
    modules.
    
    Generally speaking, I feel we should avoid recommended/optional
    dependencies unless there is a really compelling reason to
    permit users to not have them (like because they don't work
    on certain platforms or perls).

**Comment by clonezone** [comment]
Ahem. Whoops.

**Comment by thaljef** [comment]
> All recommended/optional dependencies are now required.

Yeah, that was me. Sorry I left some of the boilerplate around.

Elliot did a fabulous job rigging up tests for this. But at some point, I just decided to embrace dependencies. It made things easier for me to maintain and (usually) made the product better for users.
