### ISSUE TITLE
Issues link is wrong in Perl::Critic pod

### ISSUE THREAD

**Issue by singingfish** [Perl-Critic/Perl-Critic#768]
as subject, link does not resolve to github correctly

**Comment by petdance** [comment]
What version?  What file are you looking in?

**Comment by singingfish** [comment]
as per here https://metacpan.org/pod/Perl::Critic#BUGS

**Comment by petdance** [comment]
This has been fixed as of e48ce0e3 and will be in the next release.  Thanks.
