### ISSUE TITLE
use common::sense should satisfy "Code before strictures are enabled" (i.e. use strict; use warnings;)

### ISSUE THREAD

**Issue by AbsurdMagpieScrutinies** [Perl-Critic/Perl-Critic#772]
OK, there could be a way to make this happen using existing Perl-Critic functionality, but I don't know it.

I use 'use common::sense' at the head of short scripts, which pulls in a few common dependencies, including "use warnings (not all)" and "use strict".

I think that use common::sense should satisfy the "Code before strictures are enabled" requirement and, I suggest that maybe it is a bug that it doesn't .

But, then again, I could be completely wrong.

**Comment by petdance** [comment]
You'll need to put those in your .perlcriticrc.  Perl::Critic can't look inside common::sense and know what it's doing inside.

```
[TestingAndDebugging::RequireUseStrict]
equivalent_modules = common::sense

[TestingAndDebugging::RequireUseWarnings]
equivalent_modules = common::sense
```

**Comment by AbsurdMagpieScrutinies** [comment]
Ah, great, thanks. I looked over the man page but managed to miss ```equivalent_modules = ```

I'll close this.

**Comment by AbsurdMagpieScrutinies** [comment]
Ah, ok, I added those to my perlcriticrc, both as the only lines in the rc and by editing an rc generated by perlcritic --profile-proto, and now Perl::Critic will not catch any errors. I can use any text file as the input to the perlcritic command and it always returns <filename> source OK.

Any ideas? Could it be something absolutely bizzare with common::sense?

**Comment by petdance** [comment]
Please post specifics: Source file, perlcriticrc and command line used to invoke Perl::Critic.

**Comment by xsawyerx** [comment]
Here's my rc file, and it works just fine. While `common::sense` is not listed under warnings, it would work with any module:

```
[TestingAndDebugging::RequireUseStrict]
equivalent_modules = Dancer Dancer2 Moo Moose Moo::Role Moose::Role strictures common::sense Test::Modern

[TestingAndDebugging::RequireUseWarnings]
equivalent_modules = Dancer Dancer2 Moo Moose Moo::Role Moose::Role strictures Test::Modern
```

**Comment by AbsurdMagpieScrutinies** [comment]
@petdance 

> Please post specifics: Source file, perlcriticrc and command line used to invoke Perl::Critic.

**source file**: 

named xxx.pl

```#!/usr/bin/perl

use common::sense; 

use autodie;
use charnames   		qw< :full >;
use File::Basename      qw< basename >;
use Carp                qw< carp croak confess cluck >;
use POSIX;
use English 			qw( -no_match_vars ) ;

END { close STDOUT }
$0 = basename($0);  # shorter messages
$| = 1;					# autoflush: solving perl's stupidities 1 by 1

# --- unicode ---
binmode STDOUT, ":encoding(UTF-8)";
binmode STDERR, ":encoding(UTF-8)";
use Unicode::Normalize  qw< NFD NFC >;
use Encode              qw< encode decode >;
use open        		qw< :std  :utf8     >;




aldkfjjaldkfj 

my $xxxx

banana

my @banana

frog
```

** perlcriticrc **:

I copied in @xsawyerx 's from above:

```
me > cat ~/.perlcriticrc
[TestingAndDebugging::RequireUseStrict]
equivalent_modules = Dancer Dancer2 Moo Moose Moo::Role Moose::Role strictures common::sense Test::Modern

[TestingAndDebugging::RequireUseWarnings]
equivalent_modules = Dancer Dancer2 Moo Moose Moo::Role Moose::Role strictures Test::Modern

````

** commandline** :


```me > perlcritic xxx.pl
xxx.pl source OK
```

**Comment by petdance** [comment]
What command did you use to invoke perlcritic?

**Comment by AbsurdMagpieScrutinies** [comment]
``` > perlcritic xxx.pl ```

The xxx.pl file is clearly faulty, but the response is 

```xxx.pl source OK```

**Comment by thaljef** [comment]
That looks correct to me. At the default severity level, the only policy violated by this code would be RequireUseStrict, but you've added common::sense to the equivalent modules list, so that isn't reported. If you were expecting to see a violation of RequireUseWarnings, then lower the severity threshold like this: `perlcritic -4 xxx.pl`

**Comment by AbsurdMagpieScrutinies** [comment]
Sorry, I think I must be completely misunderstanding something here. I'm just going to accept that what you say is completely correct. 

I don't see how the (what I saw as faulty) lines \:

```  
aldkfjjaldkfj 

my $xxxx

banana

my @banana

frog

```

with a non-label identifier "aldkfjjaldkfj" and "frog" without sigils and not terminated by a semicolon, and all the subsequent lines having no semicolons, could or should pass perlcritic. 

I must be misunderstanding something. When I first used perlcritic it was enforcing the use of uppercase 'constant' variable names and the like.

**Comment by petdance** [comment]
What errors are you getting if you don't use the new perlcriticrc?

**Comment by thaljef** [comment]
> I don't see how the (what I saw as faulty) lines...with a non-label identifier "aldkfjjaldkfj" and "frog" without sigils and not terminated by a semicolon, and all the subsequent lines having no semicolons, could or should pass perlcritic.

Ah, now I understand your confusion. Perlcritic does not (and never has) enforced syntactic correctness. That job is left for the perl interpreter (like with `perl -c` or something similar).

**Comment by AbsurdMagpieScrutinies** [comment]
Ah, I had no idea. That's it. Perlcritic supplements perl -c, not improves on it. 

I'll close this. 

Possibly one line, maybe exactly what you wrote: 

> "Perlcritic does not (and never has) enforced syntactic correctness. That job is left for the perl interpreter (e.g. perl -c)."

could or should be added to the DESCRIPTION block of the perlcritic man page.
