### ISSUE TITLE
ValuesAndExpressions::ProhibitUnknownBackslash recognize \N

### ISSUE THREAD

**Issue by epa** [Perl-Critic/Perl-Critic#774]
I believe that ValuesAndExpressions::ProhibitUnknownBackslash needs to understand the \N named character escape sequence introduced in recent perls.  E.g.

    $foo = "\N{CHECK MARK}";

This with 1.126, but I do not see a fix for it in Changes of 1.127_02.

**Comment by thaljef** [comment]
That policy is from [Perl-Critic-Pulp](https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::ProhibitUnknownBackslash), not the Perl-Critic core. Please contact Kevin Ryde about that.
