### ISSUE TITLE
InputOutput::RequireCheckedOpen when opening to string

### ISSUE THREAD

**Issue by epa** [Perl-Critic/Perl-Critic#775]
I think the return value of `open` does not need to be checked here:

    my $out;
    open my $fh, '>', \$out;

It cannot fail.

**Comment by petdance** [comment]
`perldoc -f open` shows it being tested.

                # in-memory files
                open(MEMORY, ">", \$var)
                    or die "Can't open memory file: $!";
                print MEMORY "foo!\n";              # output will appear in $var

**Comment by petdance** [comment]
```
open( MEMORY, '>', \undef ) or die "Can't open: $!";
```
fails with
```
Can't open: Invalid argument at open.pl line 6.
```

**Comment by epa** [comment]
Good points.  I think that the handling in the perl core could be improved, but until then perlcritic does need to warn.

**Comment by epa** [comment]
I think the example of `\undef` is a different case to what this bug addresses though.  I mean when a reference to a scalar variable is passed.

**Comment by petdance** [comment]
I don't know that your assertion "It cannot fail." is accurate, even in the case of a `open FH, '>', \$scalar`.

**Comment by epa** [comment]
Yes, I am just guessing here -- but logically, it would only fail if there were an out of memory condition, and Perl handles those by just blowing up, not returning a neat error code.  Still it's something that the perl5-porters would have to confirm.

**Comment by petdance** [comment]
> Yes, I am just guessing here

Let's not do that.

**Comment by petdance** [comment]
```
open( MEMORY, '>', \$& ) or die $!;
```

gives

```
Modification of a read-only value attempted at open.pl line 3.
```

**Comment by petdance** [comment]
```
use Readonly;

Readonly my $foo;
open( MEMORY, '>', \$foo ) or die $!;
```
gives
```
Modification of a read-only value attempted at open.pl line 4.
```

**Comment by epa** [comment]
Yes, that dies, but it never gets as far as returning from open().
````
use Readonly;
Readonly my $foo;
open( MEMORY, '>', \$foo ) or die 'open returned false';
````

**Comment by petdance** [comment]
> Yes, that dies, but it never gets as far as returning from open().
Already deleted it.

**Comment by epa** [comment]
I'll file a bug against perl core asking whether the example in perldoc really needs to test the return status of `open()`, and if so, what are the circumstances where it could return false.  You could keep this bug open in the meantime, or close it, as you wish.

**Comment by epa** [comment]
I've sent a message to perlbug@perl.org but it hasn't showed up in the bug queue yet:

perlfunc has some example code like

````
    open(MEMORY, ">", \$var)
        or die "Can't open memory file: $!";
````

Under what circumstances would that open() call return false?
If it did return false, would the error really be in the $! variable?

I would have expected that opening a filehandle to a scalar would be
something that always succeeds, unless the scalar is readonly or
otherwise weird, in which case it just dies rather than returning
false.  So the 'or die' is redundant and somewhat misleading.

If I'm wrong, and open() to a scalar can return false for some cases,
the docs should say what those cases are.

**Comment by petdance** [comment]
[This ticket](https://rt.perl.org/Public/Bug/Display.html?id=131546) shows that it is important to check the return from `open` in this case.

**Comment by epa** [comment]
The rt.perl.org ticket doesn't (yet) show that it is important to check the return from `open` for the example program in this bug.  However, it is necessary to check if you are using some file mode other than `'>'`.
