### ISSUE TITLE
RegularExpressions::ProhibitUnusedCapture does not recognize @{^CAPTURE}

### ISSUE THREAD

**Issue by trwyant** [Perl-Critic/Perl-Critic#778]
`@{^CAPTURE}` as a synonym for `( $1, $2, ... )` was introduced in 5.26.0 (well, 5.25.7 I think). In theory it needs to be taken into account to avoid false positives from `ProhibitUnusedCapture`, though in practice this variable has had minimal time to come into actual use. A pull request to add support for this variable is in preparation (and the check is in the mail ...).

**Comment by petdance** [comment]
Merged. Thank you for the patch and the patience. d4c6deda
