### ISSUE TITLE
Question on possible adoption of policies

### ISSUE THREAD

**Issue by jonasbn** [Perl-Critic/Perl-Critic#780]
Hi,

I am considering renaming my policies, since they no longer have any affiliation with logicLAB.

So the question is, would it be of interest to Perl::Critic to adopt any of these?

- [Perl::Critic::Policy::logicLAB::ProhibitShellDispatch](https://metacpan.org/pod/Perl::Critic::Policy::logicLAB::ProhibitShellDispatch)
- [Perl::Critic::Policy::logicLAB::ProhibitUseLib](https://metacpan.org/pod/Perl::Critic::Policy::logicLAB::ProhibitUseLib)
- [Perl::Critic::Policy::logicLAB::RequireSheBang](https://metacpan.org/pod/Perl::Critic::Policy::logicLAB::RequireSheBang)
- [Perl::Critic::Policy::logicLAB::RequireVersionFormat](https://metacpan.org/pod/Perl::Critic::Policy::logicLAB::RequireVersionFormat)
- [Perl::Critic::Policy::logicLAB::RequirePackageNamePattern](https://metacpan.org/pod/Perl::Critic::Policy::logicLAB::RequirePackageNamePattern)
- [Perl::Critic::Policy::logicLAB::RequireParamsValidate](https://metacpan.org/pod/Perl::Critic::Policy::logicLAB::RequireParamsValidate)
- [Perl::Critic::Policy::logicLAB::ModuleBlacklist](https://metacpan.org/pod/Perl::Critic::Policy::logicLAB::ModuleBlacklist)

If interested please let me know. I would make the appropriate changes and create PRs, but I do not want to do all the yak shaving if there is no interest.

Looking forward to hearing from you,

jonasbn

**Comment by petdance** [comment]
Thanks for raising the flag.  I personally don't think it makes any sense to put any of these in core Perl::Critic, nor would I add any of them to my own Perl::Critic::Bangs.  I don't know what any other Perl::Critic folks think.

**Comment by jonasbn** [comment]
Thanks for the quick response, I will ponder if a rename is worth the effort.

Take care, 

jonasbn
