### ISSUE TITLE
feature request Documentation::RequirePodSections should enable exclusion

### ISSUE THREAD

**Issue by Tux** [Perl-Critic/Perl-Critic#784]
The documentation lets you select what to require:
```
           [Documentation::RequirePodSections]
           lib_sections    = NAME | SYNOPSIS | BUGS AND LIMITATIONS | AUTHOR
           script_sections = NAME | USAGE | OPTIONS | EXIT STATUS | AUTHOR
```
But it does not allow what to exclude
```
lib/DBD/CSV.pm#389.1:   [2 - Documentation::RequirePodSections] Missing "AUTHOR" section in POD :=head1 NAME
```
which is because I have
``` perl
=head1 AUTHORS and MAINTAINERS
```
So I'd like to be able to either exclude a section or have a mechanism to state that a section is named differently (on purpose)
If that is not accepted, I'd like to ask to extend the recognition of the AUTHOR section to allow AUTHORS (plural) too

**Comment by petdance** [comment]
Certainly accepting AUTHORS doesn't seem like it would be too difficult.

**Comment by clonezone** [comment]
Just set the value to the list that you want.  If you want "AUTHORS and MAINTAINERS", then use

    lib_sections    = NAME | SYNOPSIS | BUGS AND LIMITATIONS | AUTHORS and MAINTAINERS

**Comment by Tux** [comment]
@clonezone  I considered that, but that shields me from possible improvements over time. Lets assume that the best practice adds a "FOOBLE" section. If I have that list, I will never be notified. Furthermore, I have to inspect the source code of the module to check what sections it currently knows and just copy/paste that. If there is a typo, I will(have to) copy the typo and miss the possible fix.
I actually value the feedback of the community and expect most of the Critic modules to evolve over time and correct me where I am wrong. If I am absolutely sure that I am not wrong (for whatever reason), I'd like to be able to make the exception.

**Comment by clonezone** [comment]
You aren’t paying attention to the rest of the configuration of the module then.

The defaults can't change without breaking existing users. That's the reason that the `source` and `language` options were added: to allow "fixing" things without changing the defaults.

**Comment by Tux** [comment]
Seems I was having a mismatch between two .perlcritic files. Sorry for the noise. One of the two used all the right settings, the other was not yet in sync
