### ISSUE TITLE
Allow user-configuration of "use strict" equivalent modules in RequireUseStrict

### ISSUE THREAD

**Issue by petdance** [Perl-Critic/Perl-Critic#796]
RequireUseStrict currently has a list of modules that invoke `use strict`.  This list is in `@Perl::Critic::Utils::Constants::STRICT_EQUIVALENT_MODULES`.

Users should be able to configure this in their perlcriticrc files.

Also, I don't think it makes sense for the Perl::Critic maintainer(s) to be in the business of trying to decide which modules should and shouldn't be in that list.

**Comment by petdance** [comment]
It would be good if this were made easily subclassable so that someone should make their own `MyPrivate::RequireUseStrict` that didn't require configuration and also wasn't just cut & paste.

**Comment by mephinet** [comment]
As I'm the creator of one of the tickets, and volunteered there to take care of a module that collects this list, a few questions:
* What would be a sensible name for it? I'd propose Module::Equivalent...
* Should we separate `warning` and `strict` in the API of that module? Currently I'm not aware of any module that enables just one of these pragmas, but I guess the API should still separate them.

**Comment by petdance** [comment]
I'm now digging in here, and RequireUseStrict and RequireUseWarnings both  have`equivalent_modules` functionality.  It looks like this ticket is entirely unnecessary.

**Comment by xsawyerx** [comment]
Agreed. This can be closed. I use that functionality in production for a long while now.
