### ISSUE TITLE
Documentation::PodSpelling here document shows up in POD docs output

### ISSUE THREAD

**Issue by kryde** [Perl-Critic/Perl-Critic#799]
In Perl::Critic::Policy::Documentation::PodSpelling version 1.130, the bit of code which tests to see if the spell checker is available has a here document containing

    =head1 Test The Spell Command

This shows up as a heading in pod2man output (its version 4.09 with Pod::Simple 3.35), where I imagine it is not meant to.

Perhaps some string instead of here document could disguise it from the pod processors.

**Comment by petdance** [comment]
This has been fixed in the dev branch.
