### ISSUE TITLE
Can't perl Build.PL on fresh Fedora 27 install for lack of Fatal.pm

### ISSUE THREAD

**Issue by moregan** [Perl-Critic/Perl-Critic#806]
On a very-nearly-fresh Fedora 27 install (perl 5.26.1) after installing all the missing dependencies that `perl Build.PL` asked for:

```
perl Build.PL 
WARNING: the following files are missing in your kit:
    lib/Perl/Critic/PolicySummary.pod
    META.json
    META.yml
    README
Please inform the author.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Perl-Critic' version '1.123'
[moregan@moregan Perl-Critic]$ ./Build 
Building Perl-Critic
Can't locate Fatal.pm in @INC (you may need to install the Fatal module) (@INC contains: inc /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at t/ControlStructures/ProhibitNegativeExpressionsInUnlessAndUntilConditions.run.PL line 11.
```

Fatal is in core since before perl 5.6, but Red Hat doesn't including with the core perl install.  Fatal is part of autodie, which itself is in core since 5.10.1, but not part of Fedora's core install.

I don't know how far back the slicing and dicing of core perl goes, and whether whether declaring a dependency on autodie works all the way back to perl 5.6.

**Comment by petdance** [comment]
Fixed in c6cb33b.  Thanks.
