### ISSUE TITLE
cpanm Perl::Critic failing in Travis-CI

### ISSUE THREAD

**Issue by xxfelixxx** [Perl-Critic/Perl-Critic#809]
Hi,

I've included Perl::Critic as a prerequisite for my tests by including:

cpanm Perl::Critic

to my before_install block in .travis.yml

All of a sudden (yesterday), Perl::Critic stopped building successfully in Travis.

Do you have any idea why?  I see that your Travis build show success, so I'm not sure what's going on.

You can see the failed build here:  https://travis-ci.org/xxfelixxx/.dotfiles/builds/343176746

Any thoughts?

Thanks,

Felix

**Comment by xxfelixxx** [comment]
I added -v to cpanm (why didn't I think of that sooner....) and got the following test failure output:

Failed Build: https://travis-ci.org/xxfelixxx/.dotfiles/builds/343689409
Raw Log: https://api.travis-ci.org/v3/job/343689410/log.txt

t/00_modules.t ................................ 
t/00_modules.t ................................ 1/2691 # Testing Perl::Critic 1.130 with PPI 1.236 under Perl 5.014004, /home/travis/perl5/perlbrew/perls/5.14/bin/perl
t/00_modules.t ................................ 2689/2691                                                           
t/00_modules.t ................................ ok
t/00_versions.t ............................... 
t/00_versions.t ............................... 1/? 
t/00_versions.t ............................... ok
...skipping passing tests....
t/20_policy_require_consistent_newlines.t ..... ok
t/20_policy_require_tidy_code.t ............... 
t/20_policy_require_tidy_code.t ............... 1/6 
#   Failed test 'Tidy with one trailing newline'
#   at t/20_policy_require_tidy_code.t line 44.
#          got: '1'
#     expected: '0'

#   Failed test 'Tidy with two trailing newlines'
#   at t/20_policy_require_tidy_code.t line 60.
#          got: '1'
#     expected: '0'

#   Failed test 'Tidy with several trailing newlines'
#   at t/20_policy_require_tidy_code.t line 83.
#          got: '1'
#     expected: '0'

t/20_policy_require_tidy_code.t ............... 5/6 
#   Failed test 'Tidy with shell escape'
#   at t/20_policy_require_tidy_code.t line 119.
#          got: '1'
#     expected: '0'
# Looks like you failed 4 tests of 6.

                                                     
t/20_policy_require_tidy_code.t ............... Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/6 subtests 
t/92_memory_leaks.t ........................... 
                                                     
t/92_memory_leaks.t ........................... skipped: Test::Memory::Cycle requried to test memory leaks
t/gh-734.t .................................... 
t/gh-734.t .................................... 1/7 
                                                     
t/gh-734.t .................................... ok

Test Summary Report
-------------------
t/20_policy_require_tidy_code.t             (Wstat: 1024 Tests: 6 Failed: 4)
  Failed tests:  2-4, 6
  Non-zero exit status: 4
Files=40, Tests=8047, 39 wallclock secs ( 1.38 usr  0.14 sys + 37.64 cusr  1.04 csys = 40.20 CPU)
Result: FAIL
Failed 1/40 test programs. 4/8047 subtests failed.
FAIL

**Comment by petdance** [comment]
Looks like the one thing it's complaining about is in Tidy.  Has there been an update to Tidy?

**Comment by xxfelixxx** [comment]
I do an install of Perl::Tidy as the step before Perl::Critic

https://github.com/xxfelixxx/.dotfiles/blob/master/.travis.yml

**Comment by xxfelixxx** [comment]
That was it, Perl::Tidy broke it....a newer version Perl-Tidy-20180220 fixed the issue and Perl::Critic builds successfully now.

Here's the log:  https://api.travis-ci.org/v3/job/343689410/log.txt

Thanks for your help.

Felix
