### ISSUE TITLE
Improve Subroutines::ProhibitUnusedPrivateSubroutines

### ISSUE THREAD

**Issue by davorg** [Perl-Critic/Perl-Critic#811]
I've started using lazy attributes a lot in my Moo/Moose classes. And that means I have a lot of `_build_foo()` subroutines that get caught by Subroutines::ProhibitUnusedPrivateSubroutines.

I'm thinking of writing a patch for this policy that does the following:

* Adds a parameter called something like `allow_regex`
* Allows unused private subs whose names match that regex
* Defaults the regex to `^_build_\w+`

Before I spend too much time on it, I wanted to check that you'd be interesting in merging a patch along those lines.

**Comment by davorg** [comment]
See also #573

**Comment by petdance** [comment]
> Before I spend too much time on it, I wanted to check that you'd be interesting in merging a patch along those lines.

Oh, if only everyone thought that way.

I think that sounds like a fine addition, so long as we drop the regex default.  Otherwise, we're changing behavior.

**Comment by davorg** [comment]
> I think that sounds like a fine addition, so long as we drop the regex default. Otherwise, we're changing behavior.

Ok. I'll take a look over the long weekend. I agree we're changing behaviour, but in a good way :) But I'll leave that up to you.

**Comment by petdance** [comment]
> I agree we're changing behaviour, but in a good way

I'd agree if everyone everywhere were using Moose, but many people do not.

**Comment by petdance** [comment]
> I agree we're changing behaviour, but in a good way

I'd agree if everyone everywhere were using Moose, but many people do not.

Let me know if there's anything I can do to help.

**Comment by petdance** [comment]
OK, I've merged the PR.  Thanks for this.  af18acf
