### ISSUE TITLE
"Having more than one /x regexp modifier is deprecated" warning

### ISSUE THREAD

**Issue by mtmail** [Perl-Critic/Perl-Critic#822]
For Perl 5.22 and 5.24 we see `Having more than one /x regexp modifier is deprecated at [...]/Perl/Critic/Policy/ValuesAndExpressions/RequireInterpolationOfMetachars.pm line 110.`

The line is
which is https://github.com/Perl-Critic/Perl-Critic/blob/dev/lib/Perl/Critic/Policy/ValuesAndExpressions/RequireInterpolationOfMetachars.pm#L110
```perl
my $cfws           = qr/$comment|\s+/xx;
```

It's in the https://travis-ci.org/Perl-Critic/Perl-Critic output. Perl 5.26 doesn't seem to be affected.

The code section starts with
```
# Stolen from Email::Address, which is deprecated.  Since we are not modifying
# the original code at all, we are less stringent in being Critic-compliant.
```

I've never seen `/xx`. Since newest Perl is not warning I don't know if the fix is changing it to `/x` or adding a `no critic`.

**Comment by petdance** [comment]
Thanks for reporting this. We'll need to figure out if that `/xx` is needed.

**Comment by xanni** [comment]
It's a new feature in Perl 5.26: https://perldoc.perl.org/perl5260delta.html#New-regular-expression-modifier-%2fxx

But if that regex really relies on the new behaviour it will fail with Perl versions prior to 5.26, which is not good.

**Comment by petdance** [comment]
Clarifying that I understand what we think about this ticket: The code taken from Email::Address had a regex that ended in `/xx`.  It seems that that `/xx` had no effect, either positive or negative, and so it should be safe to change it just to `/x`, so it doesn't cause warnings in 5.22+.  Correct?

**Comment by xanni** [comment]
Yes, that's my understanding also.

**Comment by jonasbn** [comment]
Would it be an idea to get @reneeb to create a PR from the fix applied to his fork (see earlier in the comment), I know it might be trivial to apply the fix anyway, but still he already did the work.

**Comment by reneeb** [comment]
I can do that...

**Comment by jonasbn** [comment]
I knew it @reneeb :-)

**Comment by apparluk** [comment]
_cf_: [Moose ](https://nurmi-labs.blogspot.com/2020/01/moose.html)(blog Post)

Seems simple enough to run a `sed` command.

```
$ pushd ~/perl5/lib/perl5/Perl/Critic/Policy/ValuesAndExpressions
~/perl5/lib/perl5/Perl/Critic/Policy/ValuesAndExpressions ~
$ sed -i 's#xx#x#' RequireInterpolationOfMetachars.pm
$ popd
~
$
```

**Comment by petdance** [comment]
@apparluk When tickets don't get done for a while, it's almost never because someone couldn't do the obvious minute or two of text edits.

**Comment by apparluk** [comment]
@petdance 

In this instance running Perl v5.22.2, I sent you the shell output `more than one /x regexp modifier` before I ran a recursive `grep` on `$PERL5LIB/Perl/Critic`, and checked the GH issue tracker.

Under ordinary circumstances I'd have available the development version of the Linux distribution of choice, currently that would mean a system Perl v5.30.1, and the cited shell output wouldn't have occurred.

**Comment by apparluk** [comment]
Do the OP or circa 2019-20 comment authors factually use Perl < 5.26, and, If so are they unable to run a `sed` command prior to installing MetaCPAN modules where Perl::Critic is a dependency?

**Comment by mtmail** [comment]
OP here. We're using 5.30 these days. And patched the installation on our systems, similar to the `sed` command.

**Comment by apparluk** [comment]
```
bash-4.3$ grep xx Email-Address-1.912/lib/Email/Address.pm
bash-4.3$ 
```


Is it suitable to wholly replace in RequireInterpolationOfMetachars.pm the content from the earlier Email::Address release with the similar content from the Email-Address-1.912  file Address.pm? 

[Email::Address](https://metacpan.org/pod/Email::Address)

**Comment by petdance** [comment]
I'll try to look at this again this weekend.

**Comment by ehuelsmann** [comment]
That'd be great. However, I need no more than some direction on what additional steps need to be taken for you to be able to merge a (or the available) PR.

**Comment by petdance** [comment]
This is fixed and will be released in 1.139_01.

**Comment by robrwo** [comment]
When will this be released as a non-dev version?

**Comment by petdance** [comment]
I'll put it on my to-do list.
