### ISSUE TITLE
Support allowing subcategories of warnings

### ISSUE THREAD

**Issue by skaurus** [Perl-Critic/Perl-Critic#831]
Hi.

Right now I can't do that:

    [TestingAndDebugging::ProhibitNoWarnings]
    allow = experimental::smartmatch

and that would be nice.

**Comment by reneeb** [comment]
https://github.com/Perl-Critic/Perl-Critic/pull/892

**Comment by glauschwuffel** [comment]
Because of the comments in #892 I believe this is fixed and released, so this ticket can be closed. Am I right?

**Comment by petdance** [comment]
Thanks for catching this.
