### ISSUE TITLE
Upgrade To PPI 1.252, Fix Infinite Loop Due To Stringified '00' Exponent

### ISSUE THREAD

**Issue by wbraswell** [Perl-Critic/Perl-Critic#860]
I'm not sure which policy or policies this is triggered by specifically, but I do know it is affecting Perl::Critic because PPI is loaded as a dependency by Perl::Critic and then I subsequently see the infinite loop.  This only affects Perl 5.24 and newer.

Failing with old PPI 1.236:

https://travis-ci.org/wbraswell/physicsperl/builds/525087599

Passing with new PPI 1.252:

https://travis-ci.org/wbraswell/physicsperl/builds/525135506

More details about this bug can be found here:

https://github.com/adamkennedy/PPI/issues/229

**Comment by wbraswell** [comment]
Fix here, tests currently running:
https://github.com/Perl-Critic/Perl-Critic/commit/f6ae6433711684d8ea30e7252af9b5a1b97c390b

**Comment by wbraswell** [comment]
@petdance
Tests failing on both AppVeyor & Travis, reported to PPI maintainer @wchristian
https://github.com/adamkennedy/PPI/issues/236
https://github.com/adamkennedy/PPI/issues/237

**Comment by wbraswell** [comment]
Second commit here, upgrade to PPI 1.264 and enable verbose CPAN installation to see all errors, tests running now:
https://github.com/Perl-Critic/Perl-Critic/commit/62f5224ca85e1f16e17fb692cc3382b44ba892c1

**Comment by petdance** [comment]
@wbraswell Are you satisfied that this is fixed now?  Can I close the ticket?
