### ISSUE TITLE
Error install Perl::Critic

### ISSUE THREAD

**Issue by lbenevenuto** [Perl-Critic/Perl-Critic#872]
This is the error:

t/03_pragmas.t ................................ ok     
t/04_options_processor.t ...................... ok     
t/05_utils.t .................................. 1/156 
#   Failed test 'parse_arg_list: foo( { bar() }, {}, 'blah' )'
#   at t/05_utils.t line 433.
#     Structures begin differing at:
#          $got->[0] = ARRAY(0x561c4082ba70)
#     $expected->[0] = ' { bar() }'
# Looks like you failed 1 test of 156.
t/05_utils.t .................................. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/156 subtests 
t/05_utils_perl.t ............................. ok   
t/05_utils_pod.t .............................. ok     
t/05_utils_ppi.t .............................. ok     

Ubuntu 19.04
Perl v5.28.1

Thanks

**Comment by petdance** [comment]
This has been fixed with #863 and will be included when we make the next release.
