### ISSUE TITLE
InputOutput::ProhibitBarewordFileHandle dies on `open(CHECK, '/foo');`

### ISSUE THREAD

**Issue by petdance** [Perl-Critic/Perl-Critic#878]
Prompted by https://www.reddit.com/r/perl/comments/c4lhaq/and_most_damning_of_all_the_resulting_code_was/erx5hno/

> The punchline is, of course, the 100 kB file keeper in http://www.ibiblio.org/pub/Linux/search/keeper-1.54.tar.gz. The code is so eyewateringly bad, it crashes Perl::Critic::Policy::InputOutput::ProhibitBarewordFileHandles. esr made a career out of bashing Perl, always blaming the language, never his own lack of skill.

```
$ cat minimal
#!/usr/bin/perl

open(CHECK, '/foo');
$ perlcritic minimal -s InputOutput::ProhibitBarewordFileHandles
Fatal error while critiquing "minimal": Not an ARRAY reference at /var/perl5.20.3/lib/site_perl/5.20.3/Perl/Critic/Policy/InputOutput/ProhibitBarewordFileHandles.pm line 35.

$ perlcritic minimal -s Freenode::BarewordFileHandles
Fatal error while critiquing "minimal": Not an ARRAY reference at /var/perl5.20.3/lib/site_perl/5.20.3/Perl/Critic/Policy/Freenode/BarewordFilehandles.pm line 47.
```

See also https://github.com/Grinnz/Perl-Critic-Freenode/issues/33

**Comment by trwyant** [comment]
It looks to me like this is fallout from a PPI mis-parse -- it sees the 'CHECK' and thinks the argument list to the open is a scheduled block.

**Comment by trwyant** [comment]
And, in fact, there is an issue against PPI: https://github.com/adamkennedy/PPI/issues/246

Working around this in Perl-Critic is a couple lines of code, but of course the right place to fix this is PPI. I will look into both.

**Comment by petdance** [comment]
Thanks for your time and effort, Tom.  I'll try to keep putting out updates as you get bugs fixed.

**Comment by trwyant** [comment]
No problem. This one may take a while, because what **really** needs to happen is that PPI needs to get the parse right. Right now I'm working on that. Or, really, I have code that I hope will work and am watching the computer plow through CPAN to see what it gets wrong. There may be a Perl::Critic patch anyway, either a workaround (if I can't get PPI fixed), defensive code, or both. Don't wait up.

And I thought I was cherry-picking.

**Comment by nrathaus** [comment]
Sorry to nag, any update?

**Comment by trwyant** [comment]
Thanks for nagging. What with one thing and another this has completely dropped off my radar. I don't have a lot of free time right now, but I will see what I can do. It looks like I was trying to get a patch to PPI accepted, but I'm going to have to figure out what (if anything) happened to it.

Would you be kind enough to nag me again in a couple weeks if you don't get anything from me?

**Comment by trwyant** [comment]
It looks like I submitted a pull request to PPI ([https://github.com/adamkennedy/PPI/pull/247]) which was never acted on. I have rattled their cage in turn. I have made an entry in my tickler system for two weeks, but I'm not retracting the request that you nag me.

**Comment by petdance** [comment]
Fixed and merged. Thanks @trwyant. 16fe3c7f
