### ISSUE TITLE
Variables::ProhibitPunctuationVars wrongly (maybe) match postderef feature.

### ISSUE THREAD

**Issue by mat813** [Perl-Critic/Perl-Critic#881]
Given this code:

```
$ cat test.pl
my $array = [ 1, 2, 3, 4 ];

print join("\n", $array->@*);
```

perltidy generates a:

```
test.pl: [Variables::ProhibitPunctuationVars] Magic punctuation variable @* used at line 3, col 26: '"\n", $array->@*'.  See page 79 of PBP.  (Severity: 2)
```

See features (starting with 5.24) for the whole description of postderef, basically, it means that `$a->@*` is equivalent to `@{$a}`.

I don't think there is an English equivalent of this, so it should probably not be reported.

**Comment by xsawyerx** [comment]
I cannot recreate this failure.

**Comment by petdance** [comment]
I believe this should be handled by #578.
