### ISSUE TITLE
Tests fail, cannot install 1.132

### ISSUE THREAD

**Issue by xsawyerx** [Perl-Critic/Perl-Critic#884]
One error message:

<details>
#   Failed test 'parse_arg_list: foo( { bar() }, {}, 'blah' )'
#   at t/05_utils.t line 433.
#     Structures begin differing at:
#          $got->[0] = ARRAY(0x55c0de5d6fd0)
#     $expected->[0] = ' { bar() }'
# Looks like you failed 1 test of 156.
t/05_utils.t ..................................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/156 subtests
</details>

Warning in test:
<details>
Unhandled type: REGEXP at /home/sawyer/perl5/lib/perl5/Devel/Cycle.pm line 107.
</details>

Summary report:
<details>
Test Summary Report
-------------------
t/05_utils.t                                (Wstat: 256 Tests: 156 Failed: 1)
  Failed test:  139
  Non-zero exit status: 1
t/20_policies.t                             (Wstat: 0 Tests: 2714 Failed: 0)
  TODO passed:   2273
Files=40, Tests=8076, 32 wallclock secs ( 0.57 usr  0.04 sys + 29.56 cusr  1.67 csys = 31.84 CPU)
Result: FAIL
Failed 1/40 test programs. 1/8076 subtests failed.
</details>

PPI is up to date. (1.270)

**Comment by toddr** [comment]
I just got the same thing.

**Comment by xsawyerx** [comment]
I now have 1.134 so I guess this is no longer an issue for me. @toddr does this happen on 1.134 for you or still 1.132?

**Comment by toddr** [comment]
Correct. We should probably just close this.
