### ISSUE TITLE
Couldn't find the security theme

### ISSUE THREAD

**Issue by JStyle21** [Perl-Critic/Perl-Critic#898]
Hi,

I interested in knowing what are the policies included in the security theme you have, can anyone share this?

**Comment by petdance** [comment]
I don't believe we have any policies aimed specifically at security.  What sorts of things are you thinking of?

**Comment by JStyle21** [comment]
Anything in the OWASP Top 10 really so things like SQLI XSS etc.
But if you don't have any of that it's still fine i just found about this project and it did mention a security theme that has policies so i figured i'd ask about it.

**Comment by petdance** [comment]
Those are app-level problems, and Perl::Critic works at the language level.

That said, you may find other add-on policies for Perl::Critic by searching metacpan.org.  For example, here's an add-on that checks for SQL injection.

https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::PreventSQLInjection

Note that these add-ons are not part of Perl::Critic itself.
