### ISSUE TITLE
Can we use single quotes instead of unicode(?) quotes

### ISSUE THREAD

**Issue by willt** [Perl-Critic/Perl-Critic#910]
https://github.com/Perl-Critic/Perl-Critic/blob/b0d2ded87a25a05d42dcf8375654119def46ad58/lib/Perl/Critic/Policy/BuiltinFunctions/ProhibitShiftRef.pm#L97

On Centos7 w/ the aspell-en package installed it causes a test failure
# blib/lib/Perl/Critic/Policy/BuiltinFunctions/ProhibitShiftRef.pm: Check the spelling in your POD: alias� at line 1, column 1.  See page 148 of PBP.  (Severity: 1, Documentation::PodSpelling)

**Comment by petdance** [comment]
Done: 92955d9e

Thanks.
