### ISSUE TITLE
InputOutput::ProhibitBarewordFileHandle doesn't check opendir() but should (patch)

### ISSUE THREAD

**Issue by raforg** [Perl-Critic/Perl-Critic#912]
It would be really good if InputOutput::ProhibitBarewordFileHandle checked directory handles (opendir) as well as file handles, especially since perl7 probably won't accept them either. Here's a patch (policy, manpage, tests)
[Perl-Critic-1.138-ProhibitBarewordFileHandles-opendir.diff.gz](https://github.com/Perl-Critic/Perl-Critic/files/4906111/Perl-Critic-1.138-ProhibitBarewordFileHandles-opendir.diff.gz)

.

**Comment by petdance** [comment]
I think that if we add the functionality to check for bareword dir handles, we should make it a different policy, rather than overload the existing one.

**Comment by petdance** [comment]
To be clear: I think it would be good to do.  I just think it should be a separate policy.

**Comment by raforg** [comment]
That seems to presume that someone exists out there who would want to be notified about one version of this issue but not the other. I think that's very unlikely. I thought it best to include the functionality in the policy that was already recommended by brian d foy in his book "Preparing for Perl7". But if you won't accept it as is, I could copy and paste it to create a whole new policy and ask brian to include it in his perl7 theme (but that seems like the wrong thing to do). Is it possible to create a policy that is a set of two other policies, so that everyone who wants both versions of the issue to be checked only needs to add a single policy to their .perlcriticrc theme? But even then, there are existing bugs that would then need to be fixed in two separate policies rather than in just one. And having it as two separate policies would run more slowly than a single policy. I don't see the value in making them separate. And there should be value to justify the additional work (even the user would face additional work since they have to add two policies to their .perlcriticrc  rather than just one).

**Comment by raforg** [comment]
If you'd still prefer a separate policy for this, I'll try to fix the reported bugs in the original policy first, before cutting and pasting it into a new policy (but I'll have to learn about PPI first).

**Comment by raforg** [comment]
Actually, it looks like that/those bug(s) were already fixed and are awaiting new documentation relating to typeglobs. I'd be willing to add new examples of what is or isn't excluded to the policy's documentation, and add new tests (if that pull request doesn't already include them), but I can't provide the explanation that you're hoping for.

**Comment by raforg** [comment]
I've created a pull request adding the new policy.

**Comment by raforg** [comment]
I think I've done something wrong with the pull request. Appveyer is saying:

Switched to branch 'dev'
fatal: Could not parse object '38a572d1e9cae67b731cdfa05e2ffe8a98ca0a1f'.
Command exited with code 128

Should I have created a new branch first? I just committed to the dev branch in my fork.

**Comment by raforg** [comment]
Appveyer seems happy with it now.

**Comment by petdance** [comment]
Are we sure that we're not already checking for this?

I just got this warning on some code at work

```
program_name: Using bareword filehandles.
    52:opendir(InputDir,$inputdir) or do {
```

**Comment by raforg** [comment]
Yes, I'm sure. That error message isn't coming from ProhibitBarewordFileHandles.pm. Its violates() function has:

    return if $elem->content() ne 'open';

Also, its error message would look something like:

    Bareword file handle opened at line 610, column 2.  See pages 202,204 of PBP.  (Severity: 5)

I suspect that the error message you saw might be coming from the use of:

    no bareword::filehandles

Is that possible? It's just a guess. Was the program running at the time, or was perlcritic running at the time?

I also noticed that ProhibitBarewordFileHandles doesn't check sysopen() either but should.
Would you be receptive to a patch to include that in the existing ProhibitBarewordFileHandles policy?
It's attached. I can create a pull request for it.

[ProhibitBarewordFileHandles.pm.with_sysopen.patch.gz](https://github.com/Perl-Critic/Perl-Critic/files/4957062/ProhibitBarewordFileHandles.pm.with_sysopen.patch.gz)
