### ISSUE TITLE
Let Perl::Critic::Policy::Documentation::RequirePackageMatchesPodName pass if package name is formatted (wish list)

### ISSUE THREAD

**Issue by LadyAleena** [Perl-Critic/Perl-Critic#913]
One rule I follow when writing is to put the title of the document, in this case the package name, in bold in the first paragraph. However, this leads to my modules failing this test every time. So, could the test check for the package name within formats?
```perl
=head1 NAME
B<Package::Name> does neat stuff.
```
I have version 1.138 of Perl::Critic::Policy::Documentation::RequirePackageMatchesPodName

**Comment by petdance** [comment]
This has been fixed on dev and will be released in 1.139_01.
