### ISSUE TITLE
Prevent execution of BEGIN / INIT / CHECK / UNITCHECK blocks

### ISSUE THREAD

**Issue by HaleTom** [Perl-Critic/Perl-Critic#924]
I want to check my `perl` code without opening myself up for executing code in `BEGIN` / `UNITCHECK` blocks.

[ALE, a `vim` linter, warns the following](https://github.com/dense-analysis/ale/blob/master/doc/ale-perl.txt):

> ALE offers a few ways to check Perl code. Checking code with `perl` is
disabled by default, as `perl` code cannot be checked without executing it.
Specifically, we use the `-c` flag to see if `perl` code compiles. This does
not execute all of the code in a file, but it does run `BEGIN` and `CHECK`
blocks. See `perl --help` and https://stackoverflow.com/a/12908487/406224

[This perlmonks post](https://www.perlmonks.org/?node_id=853778) also shows that `CHECK` and `INIT` blocks can be executed under some circumstances.

How can I check `perl` code without running any of it?

Prior and related art:
* [Same question on StackExchange](https://stackoverflow.com/questions/63741274/prevent-compile-linting-execution-of-begin-unitcheck-blocks)
* [`perltidy` issue](https://github.com/perltidy/perltidy/issues/36)

**Comment by petdance** [comment]
Perl::Critic will do static analysis of your code, but it is definitely not a syntax checker.  Still, I encourage you to install and try Perl::Critic for analysis on your code.
