### ISSUE TITLE
ProhibitUnusedPrivateSubroutines can't tell when overriding a base class method

### ISSUE THREAD

**Issue by epa** [Perl-Critic/Perl-Critic#926]
If you make a derived class (with `use parent` or whatever) and just override method `_foo` from the base class, ProhibitUnusedPrivateSubroutines will think it's unused.  It is called, just not in this source file.

Perhaps it's bad practice to override private methods in derived classes (I would say it all depends) but that would be a different policy, not flagging as 'unused'.

This with 1.138.

**Comment by glauschwuffel** [comment]
My attempt to reproduce goes like this:
```$ cat A.pm
package A;

sub _private { return 1 }

1;

$ cat B.pm
package B;

use parent 'A';
sub _private { return shift->SUPER::_private }
sub public { return shift->_private }

1;

$ perlcritic -s ProhibitUnusedPrivateSubroutines A.pm
Private subroutine/method '_private' declared but not used at line 3, column 1.  Eliminate dead code.  (Severity: 3)
```

**Comment by petdance** [comment]
> Perhaps it's bad practice to override private methods in derived classes (I would say it all depends) but that would be a different policy, not flagging as 'unused'.

And there is a policy that checks for calling private methods.

As @glauschwuffel says, I suspect this is something that we can't do reliably statically.  Also, it would require analyzing multiple files, not just the one file we're looking at.

**Comment by epa** [comment]
Could I ask why this was closed?  I believe it is still giving false positives.  Here's a real world example where I have made a derived class from a CPAN module in order to override one method:

```
package Text::CSV::Simple::FromLines;
use parent 'Text::CSV::Simple';
sub new {
    my ($class, @lines) = @_;
    my $self = $class->SUPER::new;
    bless $self, $class;
    $self->{lines} = \@lines;
    return $self;
}

# Override private method in base class.
sub _contents {
    my $self = shift;
    return @{$self->{lines}};
}

1;
```

Saved as file `x` you get

```
% perlcritic --single-policy Subroutines::ProhibitUnusedPrivateSubroutines x
Private subroutine/method '_contents' declared but not used at line 12, column 1.  Eliminate dead code.  (Severity: 3)
```

**Comment by epa** [comment]
I agree with @petdance: "this is something that we can't do reliably statically".  I suggest that means the policy should be retired.
