### ISSUE TITLE
RequireEndWithOne confused by Future::AsyncAwait

### ISSUE THREAD

**Issue by mavit** [Perl-Critic/Perl-Critic#929]
Module Future::AsyncAwait introduces a new `async` keyword.

The following code confuses `perlcritic --severity=4` into saying `Module does not end with "1;" at line 7, column 1.  Must end with a recognizable true value.`:
```perl
package test;

use strict;
use warnings;
use Future::AsyncAwait;

async sub test {}

1;
```

**Comment by petdance** [comment]
Thanks for the report.

Perl::Critic (and the underlying PPI) doesn't know about Future::AsyncAwait.  It's going to see that as invalid syntax.  This is not something that Perl::Critic can handle.
