### ISSUE TITLE
Weird Interaction with Method::Signatures cpan modules

### ISSUE THREAD

**Issue by gauthamchellu** [Perl-Critic/Perl-Critic#933]
When I run the following piece of code with Perl::Critic

```
package One;

use strict;
use warnings;
use Method::Signatures::Simple;

func PerlFunc ($one, $two) {
}

1;
```

I get an error that "Module does not end with 1;" even though it does.

**Comment by petdance** [comment]
That's because Perl::Critic doesn't know, and cannot know, what magic Method::Signatures::Simple is doing to make "func PerlFunc($one,$two)" work.  It's not valid Perl code so Perl::Critic can't be expected to parse it.

Sorry, but this is one of the limitations of doing static analysis.
