### ISSUE TITLE
/xx may cause warnings

### ISSUE THREAD

**Issue by eserte** [Perl-Critic/Perl-Critic#943]
The line https://metacpan.org/release/Perl-Critic/source/lib/Perl/Critic/Policy/ValuesAndExpressions/RequireInterpolationOfMetachars.pm#L110 has the x modifier doubled, which may cause warnings in some perl versions (seen in perl 5.22 and 5.24):
```
Having more than one /x regexp modifier is deprecated at /usr/perl5.24.4p/lib/site_perl/5.24.4/Perl/Critic/Policy/ValuesAndExpressions/RequireInterpolationOfMetachars.pm line 110.
```
See also https://rt.cpan.org/Ticket/Display.html?id=127777

**Comment by petdance** [comment]
This is the same as #822 that has been fixed and released.
