### ISSUE TITLE
Is Test::Perl::Critic::Policy still alpha quality?

### ISSUE THREAD

**Issue by oalders** [Perl-Critic/Perl-Critic#947]
At https://metacpan.org/pod/Test::Perl::Critic::Policy#DESCRIPTION I read:

> NOTE: This module is alpha code -- interfaces and implementation are subject to major changes. This module is an integral part of building and testing Perl::Critic itself, but you should not write any code against this module until it has stabilized.

This module has been around for a while. Should this warning be removed?

> commit 76d741ca909e00fdd784c0ac024bff9a252552b7
> Author: Elliot Shank <perl@galumph.com>
> Date:   Fri Oct 2 22:31:13 2009 +0000

**Comment by petdance** [comment]
Thanks, I've removed that paragraph.
