### ISSUE TITLE
Perl::Critic::Utils: pointing to perl 5.8.8 seems to be wrong

### ISSUE THREAD

**Issue by eserte** [Perl-Critic/Perl-Critic#951]
The Perl::Critic::Utils documentation https://metacpan.org/pod/Perl::Critic::Utils#is_perl_builtin(-$element-) states multiple times that syntax elements are checked as in perl 5.8.8. However, this is not true --- the current perl is used for the checks.

The difference may be seen with `is_perl_bareword()` and the new "try" bareword (experimental since perl 5.33.7, but already listed in B::Keywords as a bareword for perl 5.33.7+):
```
$ perl5.33.6 -MPerl::Critic::Utils=is_perl_bareword -MPPI::Token::Word -E 'say is_perl_bareword(PPI::Token::Word->new("try")) ? "yes" : "no"'
no
$ perl5.33.7 -MPerl::Critic::Utils=is_perl_bareword -MPPI::Token::Word -E 'say is_perl_bareword(PPI::Token::Word->new("try")) ? "yes" : "no"'
yes
```
So probably instead of "defined in Perl 5.8.8" the documentation should probably use "defined in the currently used perl version" or so.

**Comment by petdance** [comment]
Related: #994

**Comment by petdance** [comment]
Done. 7a647122  Thank you.
