### ISSUE TITLE
Error calling all_perl_files with -T switch: Insecure dependency in chdir while running with -T switch

### ISSUE THREAD

**Issue by sidney** [Perl-Critic/Perl-Critic#982]
I reproduced this with this one-liner in versions 1.138 and 1.140

$ `perl -T -MPerl::Critic::Utils -e 'all_perl_files(".");'`
Insecure dependency in chdir while running with -T switch at /usr/share/perl/5.30/File/Find.pm line 282.

There are two different line numbers depending on whether there are any subdirectories in the current directory "." but the message is otherwise the same. 

Running without the -T option produces the expected result of no output.

I think that the call to File::Find::find() in  all_perl_files() should be passed the untaint option. I"ll submit a PR for it.

**Comment by petdance** [comment]
Done, thank you.
