### ISSUE TITLE
$SEVERITY_* constants backwards?

### ISSUE THREAD

**Issue by GeekRuthie** [Perl-Critic/Perl-Critic#985]
In Perl::Critic::Utils, beginning at line 184:
```
Readonly::Scalar our $SEVERITY_HIGHEST => 5;
Readonly::Scalar our $SEVERITY_HIGH    => 4;
Readonly::Scalar our $SEVERITY_MEDIUM  => 3;
Readonly::Scalar our $SEVERITY_LOW     => 2;
Readonly::Scalar our $SEVERITY_LOWEST  => 1;
```

This is *exactly backwards* from perlcritic (the command) usage, is it not?  I tried using these when writing a pair of new policies, using _HIGH and _LOW for the default_severity, and sure 'nuf, they came out backwards when I ran perlcritic against an offending module.

**Comment by GeekRuthie** [comment]
Never mind....thinking it through, this is correct.  Assigning _LOW to the lower-priority one will cause it to only be used when --cruel is used, which is what I want.  Never mind me, nothing to see here.

**Comment by petdance** [comment]
FYI, this confusion about low vs. high severity has been around since Perl::Critic started. It pops up every few years where someone says we should change it and then we decide there's not a better way to do it.
