### ISSUE TITLE
Consider dropping "use base" suggestion from Perl::Critic::Policy::ClassHierarchies::ProhibitExplicitISA in favor of "use parent"

### ISSUE THREAD

**Issue by burak** [Perl-Critic/Perl-Critic#986]
Hi,

I'd like to resurface the things discussed in https://github.com/Perl-Critic/Perl-Critic/issues/441

This part
```
Readonly::Scalar my $DESC => q{@ISA used instead of "use base"};
```

Either needs to be 

```
Readonly::Scalar my $DESC => q{@ISA used instead of "use parent"};
```

Or it needs to be configurable. "base" fell out of favor more than a decade ago and "parent" took over, so this policy is suggesting an obsolete practice.

Likely Perl::Critic itself needs to drop "use base" as well but that's out of scope for this.

**Comment by petdance** [comment]
I shudder to think what would happen if we just changed it from requiring "use base" to "use parent". But I do think that it's what folks ought to do. I'm open to ideas to make this change not be catastrophic.

**Comment by thaljef** [comment]
At one time, this is where we put policies that had fallen out of favor: https://metacpan.org/pod/Perl::Critic::Deprecated

That way, folks can still maintain consistent rules while still upgrading to newer versions of Perl-Critic. I think we also gave them all a `deprecated` theme.

**Comment by petdance** [comment]
Perl::Critic now uses `parent` everywhere.

The policy now recommends `parent` instead of `base`.

#987
